### ISSUE TITLE
cocoapods-acknowledgements no present in repo

### ISSUE THREAD

**Issue by davidrothera** [CocoaPods/cocoapods-acknowledgements#10]
`ERROR:  Could not find a valid gem 'cocoapods-acknowledgements' (>= 0) in any repository`

Looks like the Gem isn't published, or not published anymore.

**Comment by orta** [comment]
It's not on rubygems, it probably doesn't need much work to become production worthy though

**Comment by segiddins** [comment]
@orta please summarize what needs to be done for a release to make sense?

**Comment by orta** [comment]
This is waiting on the last two issues in the milestone: https://github.com/CocoaPods/cocoapods-acknowledgements/milestones/1.0

**Comment by danielgalasko** [comment]
Any updates?

**Comment by hwaxxer** [comment]
Maybe just publish existing code as a first release? :muscle:

**Comment by orta** [comment]
OK, I've done pushed 1.0.0

**Comment by orta** [comment]
And yeah, sorry that took so long...
