### ISSUE TITLE
Check if there are any pods in a target

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-acknowledgements#11]
When running against [Artsy/Eigen](https://github.com/artsy/eigen/tree/orta-ack) it would generate a plist for a target with no pods.

![screen shot 2015-07-14 at 16 56 20](https://cloud.githubusercontent.com/assets/49038/8677831/45094a58-2a49-11e5-936e-e06709b9d174.png)

**Comment by segiddins** [comment]
Why shouldn't it generate a file?

**Comment by orta** [comment]
In this case? There is no `Pods` project, the podfile is basically:

```ruby

plugin 'cocoapods-acknowledgements', :settings_bundle => true , :settings_post_process => Proc.new { |settings_plist_path|
  puts "ACK" 
  puts settings_plist_path
}


target 'Artsy' do
   ...
end

target 'Artsy Tests' do
   ...
end

```

**Comment by segiddins** [comment]
Ahhhh ok. Not super-important, imho.

**Comment by orta** [comment]
True, but it's useful polish
