### ISSUE TITLE
Exclude certain Pods from Acknowledgements

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/cocoapods-acknowledgements#16]
Without the ability for Podspecs to opt-out of this stuff, we need some way to remove private pods and other pods that don't require attribution.

Proposal:

```ruby
plugin 'cocoapods-acknowledgements', :settings_bundle => true, :exclude => 'PrivateKit'
```

```ruby
plugin 'cocoapods-acknowledgements', :settings_bundle => true, :exclude => ['PrivateKit', 'SecretLib']
```

**Comment by orta** [comment]
Agree, and agree on supporting both singular and array forms.

**Comment by marcelofabri** [comment]
Would it make sense to scope this according to the target (like `settings_post_process`)?

**Comment by danielgalasko** [comment]
+1
