### ISSUE TITLE
Parse Podspec.description as Markdown 

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-acknowledgements#2]
Even in the simple example we have someone using markdown in the long description.

**Comment by marcelofabri** [comment]
@orta: can you give more details about this?

**Comment by orta** [comment]
The description attribute in the Podspec supports markdown, right now we are putting raw markdown in to the acknowledgements bundle, but ideally it should be pre-parsed so that people don't have to have a markdown parser in their CocoaPods dependencies.

**Comment by marcelofabri** [comment]
Should we parse to html? Or just strip the markdown annotations?

Are the answers the same for both formats (the new plist and the one for Settings.bundle)?

**Comment by orta** [comment]
Great questions. Settings bundles can't show HTML, so that ideally should be stripped. The new plists are probably showing in webviews, so I think rendering those as HTML should be :+1: 

[RedCarpet](http://stackoverflow.com/questions/2547343/markdown-to-plain-text-in-ruby) seems to be able to deal with both case - so it may be an option :+1:

**Comment by marcelofabri** [comment]
I've created a PR (#15), but I remembered that we don't show the description inside a settings bundle, so I didn't have to strip it.

Is `description` the only Podspec field that supports Markdown? I haven't found this info in [the guides](https://guides.cocoapods.org/syntax/podspec.html).
