### ISSUE TITLE
Settings bundle compatible plist not actually used

### ISSUE THREAD

**Issue by masaniemi** [CocoaPods/cocoapods-acknowledgements#20]
It seems that even though I use the ":settings_bundle => true" setting, the plugin does not really use the metadata generated by SettingsPlistGenerator for anything. Instead, it simply copies the previously generated full podspec metadata list to settings.bundle dir.

**Comment by marcelofabri** [comment]
This is actually true :astonished: 

Sorry for the delay. Can you check if https://github.com/CocoaPods/cocoapods-acknowledgements/pull/21 solves the issue?

**Comment by masaniemi** [comment]
Thanks for the fix! Unfortunately I had to go with a different solution for the acknowledgements listing, but this definitely seems like the correct fix to me.

**Comment by marcelofabri** [comment]
I'm closing this issue then. Please feel free to reopen or open another one if you find the fix wasn't enough. Thanks for reporting this!
