### ISSUE TITLE
xcproj not running

### ISSUE THREAD

**Issue by virtru-bjost** [CocoaPods/cocoapods-acknowledgements#29]
Cocoapods is supposed to run xcproj to convert the .xcproj file to ASCII instead of XML. However when using 

```plugin 'cocoapods-acknowledgements', :settings_bundle => true```

in the podfile, this does not happen and the .xcproj stays in xml form instead of converting back to ASCII form. This causes major merge issues and makes merging a headache.

**Comment by segiddins** [comment]
CocoaPods hasn't used xcproj for over a year.

**Comment by virtru-bjost** [comment]
How come the acknowledgements plugin then changes everything to xml instead of leaving it ASCII?

**Comment by segiddins** [comment]
I don't know -- can you share an example project that demonstrates the issue?

**Comment by virtru-bjost** [comment]
sure, give me a few days to get some downtime and create one.

**Comment by BarakatX2** [comment]
I had the same issue. I've attached an example project. 
[demo-plugin-bug.tar.gz](https://github.com/CocoaPods/cocoapods-acknowledgements/files/259958/demo-plugin-bug.tar.gz)

Steps:
```
tar -xf demo-plugin-bug.tar.gz
cd DemoPluginBug/
cat DemoPluginBug.xcodeproj/project.pbxproj # not xml
pod install
cat DemoPluginBug.xcodeproj/project.pbxproj # now xml
```

Xcode Version 7.3 (7D175)
[local-gems.txt](https://github.com/CocoaPods/cocoapods-acknowledgements/files/259981/local-gems.txt)

**Comment by marcelofabri** [comment]
@BarakatX2 there's an issue with `xcodeproj 0.28.2`, which CocoaPods 0.39 uses. Please update CocoaPods (and cocoapods-acknowledgements) to 1.0.0 to fix it.
