### ISSUE TITLE
Lot of empty spaces between title and licence  

### ISSUE THREAD

**Issue by rockylive** [CocoaPods/cocoapods-acknowledgements#34]
![13](https://cloud.githubusercontent.com/assets/3789511/17884105/feb5afb2-6933-11e6-9e87-6f8115216f84.png)

**Comment by rockylive** [comment]
related : http://stackoverflow.com/questions/33881111/why-does-acknowledgements-plist-from-cocoapods-look-messed-up-on-ios-9-and-what

**Comment by orta** [comment]
Looks like this is an iOS bug, rather than a problem for CP-ack - thanks for making it known to us though
