### ISSUE TITLE
Not able to install gems on OS X EL Capitan 10.11.6

### ISSUE THREAD

**Issue by adongarwar** [CocoaPods/cocoapods-acknowledgements#36]
I get following errors when i try installing using following command -
sudo gem install cocoapods-acknowledgements -n /usr/local/bin

Someone-MacBook-Pro% sudo gem install cocoapods-acknowledgements -n /usr/local/bin
Building native extensions.  This could take a while...
ERROR:  Error installing cocoapods-acknowledgements:
    ERROR: Failed to build gem native extension.

```
current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet
```

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20161017-15079-ky35vq.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet
make "DESTDIR="
make: **\* No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by`autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/redcarpet-3.3.4/gem_make.out

**Comment by amorde** [comment]
Going to close this as this is pretty old, and looks like a Ruby environment issue.
