### ISSUE TITLE
can I modify only one target?

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/cocoapods-acknowledgements#46]
I love the plugin, but it's creating files in my "Test" target. I'd like for it to *not* do that.

Is there a way I can have the `cocoapods-acknowledgements` plugin only add files to a single target? Or, barring that, remove the files that it creates from the "Test" target?

**Comment by orta** [comment]
I think it'd be reasonable to never add acknowledgements to the test target, should be pretty easy to filter the current targets down by their type and specifically remove things like extensions/tests etc
