### ISSUE TITLE
Support old style settings bundle & Markdown

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-acknowledgements#6]
Markdown should probably also have a rendered version too.

**Comment by orta** [comment]
To support the old style settings, you would need to add another section like [this](https://github.com/CocoaPods/cocoapods-acknowledgements/blob/master/lib/cocoapods_acknowledgements.rb#L14-L18) that created a settings bundle compatible version. You can see the old one here: https://github.com/CocoaPods/CocoaPods/tree/master/lib/cocoapods/generator/acknowledgements

**Comment by marcelofabri** [comment]
Do you think that the old style format be generated on its own class or in `PlistGenerator`?

**Comment by orta** [comment]
I think we could have it as a separate class "SettingsPlistGenerator"
