### ISSUE TITLE
Add the target name as param to settings_post_process

### ISSUE THREAD

**Issue by marcelofabri** [CocoaPods/cocoapods-acknowledgements#8]
The post-processing could be different according to the target.

**Comment by orta** [comment]
I agree :+1:

**Comment by marcelofabri** [comment]
Just the label or the entire [`Pod::Installer::HooksContext::UmbrellaTargetDescription`](http://www.rubydoc.info/gems/cocoapods/Pod/Installer/HooksContext/UmbrellaTargetDescription)?

**Comment by orta** [comment]
I think passing the umbrella target desc would work best
